# Public Facing Work

## Static Websites With Hugo {#hugo}

- your organization needs a basic, fast, secure website that is aesthetically pleasing
- add soundcite to your site (embedding audio in the text)

### Adding a Leaflet.js Map 

- some basics

## Building a Collections Website with CollectionBuilder {#collectionbuilder}

- you have wonderful materials. Showcase them. 
- also makes your data available in a variety of useful formats

## Omeka for Exhibitions {#omeka}

- Tell stories about your materials, pulling them together from your collection's materials
- Neatline?
- Omeka.net versus hosting your own

## Visual Storytelling with Mural {#mural}

- Long-form storytelling

## Exhibits with Wax {#wax}

- why and when you might use Wax

## Mukurtu {#mukurtu}

- Differing communities have differing protocols about access to cultural heritage information. Mukurtu is built with this in mind.

## Bots {#bots}

- Some simple bots that can make your materials more accessible
- powered by the API that datasette made available to you

## Something something Linked Open Data?

- this might be a step too far

## Interactive (Non-)Fiction {#interactive-stories}

- Tell interactive stories using Twine or Ink or Ren'Py

# Templates & Other Useful Materials {#templates}

On this page will be links to templates for wrangling metadata, etc.